### ISSUE TITLE
[feat] 프로젝트 셋업

### ISSUE THREAD

**Issue by GHeeJeon** [invisible-hands/frontend#1]
- [x] `vite` 설치
- [x] `commitlint`, `JS style guide` 를 비롯한 lint 설정
- [x] `tailwind` 설치
- [x]  `react-router-dom` 설치
- [x]  `axios`설치
- [x] `Prettier`설치
- [x]  상태 관리 `React Query` 설치

**Comment by deartomefirst** [comment]
dc2cf7b91c3da2a489352045c16b837fae7b3d41 커밋 메시지 템플릿도 추가
